resources:
- name: api-repo
  type: git
  source:
    uri: https://github.com/sabamiso7502/MockAPI.git
    branch: master

jobs:
- name: build
  public: true
  plan:
    # resourceで定義した名前を指定し、コンテナ内でgitのソースを取得する
    - get: api-repo
      resource: api-repo
      trigger: true
    - task: build
      # file: api-repo/.concourse/tasks/build.yml
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: mcr.microsoft.com/dotnet/core/sdk
            tag: 3.1-buster
        inputs:
          - name: api-repo
        run:
          path: ls