resources:
- name: api-repo
  type: git
  source:
    uri: https://github.com/sabamiso7502/MockAPI.git
    branch: master

jobs:
- name: build
  public: true
  plan:
    # resourceで定義した名前を指定し、コンテナ内でgitのソースを取得する
    - get: api-repo
      resource: api-repo
      trigger: true
    - task: build
      file: api-repo/.concourse/task/build.yml